#!/bin/bash

mv "./scan-sidea-10.tiff" "./scan-10-sidea.tiff"
mv "./scan-sidea-1.tiff" "./scan-1-sidea.tiff"
mv "./scan-sidea-2.tiff" "./scan-2-sidea.tiff"
mv "./scan-sidea-3.tiff" "./scan-3-sidea.tiff"
mv "./scan-sidea-4.tiff" "./scan-4-sidea.tiff"
mv "./scan-sidea-5.tiff" "./scan-5-sidea.tiff"
mv "./scan-sidea-6.tiff" "./scan-6-sidea.tiff"
mv "./scan-sidea-7.tiff" "./scan-7-sidea.tiff"
mv "./scan-sidea-8.tiff" "./scan-8-sidea.tiff"
mv "./scan-sidea-9.tiff" "./scan-9-sidea.tiff"
mv "./scan-sideb-10.tiff" "./scan-10-sideb.tiff"
mv "./scan-sideb-1.tiff" "./scan-1-sideb.tiff"
mv "./scan-sideb-2.tiff" "./scan-2-sideb.tiff"
mv "./scan-sideb-3.tiff" "./scan-3-sideb.tiff"
mv "./scan-sideb-4.tiff" "./scan-4-sideb.tiff"
mv "./scan-sideb-5.tiff" "./scan-5-sideb.tiff"
mv "./scan-sideb-6.tiff" "./scan-6-sideb.tiff"
mv "./scan-sideb-7.tiff" "./scan-7-sideb.tiff"
mv "./scan-sideb-8.tiff" "./scan-8-sideb.tiff"
mv "./scan-sideb-9.tiff" "./scan-9-sideb.tiff"

